### ISSUE TITLE
Support Multi Document Parsing

### ISSUE THREAD

**Issue by loligans** [xoofx/Tomlyn#31]
Does Tomlyn support Multidocument parsing?

It would be nice to do something like 
`$import = './pathto/othertoml.toml'`

**Comment by xoofx** [comment]
Multidocument doesn't seem to be the right qualification. See [here](https://github.com/toml-lang/toml/issues/583)

What you are asking is for import/include of TOML.

There is no such thing in the spec to do that and I believe it can be done entirely at the application level: e.g you deserialize to TOML and then interpret some fields as actually include of TOML. Then, it's up to you to define what does it mean to include them (inline values or not, expand to an object...etc.)

Closing because that's not something that should be part of Tomlyn itself.
