### ISSUE TITLE
Feature request: Method to write a model tree to string/file

### ISSUE THREAD

**Issue by klapstoelpiloot** [xoofx/Tomlyn#5]
Right now it seems only a DocumentSyntax can be serialized to a TOML string, but there doesn't seem to be a way to serialize a (root) TomlTable to TOML string (or to intermediate DocumentSyntax).

It would be nice to have a method to serialize a TomlTable to TOML string.

**Comment by Pilvinen** [comment]
This is long overdue. Now is the time to do it. No more clumsy hacks to preserve comments, etc.

**Comment by xoofx** [comment]
> This is long overdue. Now is the time to do it. No more clumsy hacks to preserve comments, etc.

I personally don't have time for this issue, but as it is an OSS project, PR are welcome.

The problem is non trivial: TomlTable is a loosing entirely the information of all the spaces, comments...etc. and it's not a place to retro-fit this information easily. The solution could be to provide higher level editing methods to DocumentSyntax.

**Comment by Pilvinen** [comment]
"Support perfect load/save roundtrip while preserving all spaces, new line, comments"

Then how is this accurate (from the description)? Unless you just load TOML, do nothing to it, and then write it back as a string. I don't see how I can use it that way.

**Comment by Pilvinen** [comment]
Instead of that high level ideal stuff I would just read the .toml line by line and then you do your usual stuff to the proper objects, and when you hit comments I would store them in the "table" dictionary as comment+line number and store the comment itself as the value. Then I would simply have an optional method to output the comments too.

Probably a 5 minute job when you already know the code base.

Ideal solution? Probably not. But can we really always afford to be idealists? Like you said, you don't have the time to do it properly. But if it only takes 5-10 minutes ... and it works ... and if someone hates that - as you said, it's open source and can always be refactored to use a more full solution.

The only reason why I started using this library was because it was advertised as supporting the full load/save roundtrip "Yes, finally someone gets it", and imagine my disappointment ...

**Comment by xoofx** [comment]
> Then how is this accurate (from the description)? Unless you just load TOML, do nothing to it, and then write it back as a string. I don't see how I can use it that way.

You can modify it with DocumentSyntax. It is more laborious but it is working. That's how I have been using the library when I required round-trip.

> The only reason why I started using this library was because it was advertised as supporting the full load/save roundtrip "Yes, finally someone gets it", and imagine my disappointment ...

Again, the roundtrip is supported by DocumentSyntax. It is accurate.
Otherwise, welcome to OSS. Either you help the project, or find another project. 

This problem is not a "5 minute job" because I would have done it in the first place. It is several hours of work to make it viable. Because I'm currently not using the library, I don't have a need for this, but I can't spend hours to fix something for you. I'm maintaining several OSS projects where I have put hundred of hours of work in them, for free for the .NET community.

**Comment by Pilvinen** [comment]
> the roundtrip is supported by DocumentSyntax
Maybe I'm blind but I can't find any example of that in the documentation. And after studying the objects and IDE docs for ~45 minutes I can't figure out how to unwrap the `DocumentSyntax` object into something useful.

The only way I've managed to get things working is simply reading as TOML, using `ToModel()` to turn it into an object, and then doing what I want to do and iterating through the dictionary and using StringBuilder to custom build the output.

If there's an easier way I would appreciate a brief example in the readme. The DocumentSyntax is not as intuitively easy to use as the object.

**Comment by xoofx** [comment]
I had a personal usage for this, so I brought support for it. This is available in Tomlyn >= `0.9.0`. You have now methods `Toml.FromModel(object)` to serialize back to a string.

See [documentation](https://github.com/xoofx/Tomlyn/blob/main/doc/readme.md) for more details.
